name: Build UTBot and run unit tests

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      # It is impossible to parametrize image via workflow environment,
      # so its name is hard-coded.
      # https://github.com/actions/runner/issues/480
      image: ghcr.io/unittestbot/utbotcpp/base_env:20-10-2021
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        UTBOT_ALL: /utbot_distr
        UTBOT_INSTALL_DIR: /utbot_distr/install
        GRPC_PATH: /utbot_distr/install
        CLI_PATH: /utbot_distr/cli
    steps:
      - name: Install git
        run: |
          apt install -y software-properties-common
          apt update
          add-apt-repository -y ppa:git-core/ppa
          apt update
          apt install -y git
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build UTBot and run unit tests
        run: |
          source docker/building_dependencies/runtime_env.sh
          chmod +x build.sh
          ./build.sh
          cd server/build
          chmod +x UTBot_UnitTests
          ./UTBot_UnitTests info --log `pwd`
        shell: bash
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: UTBot unit tests logs
          path: server/build/logs