name: Build UTBot and run unit tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      # It is impossible to parametrize image via workflow environment,
      # so its name is hard-coded.
      # https://github.com/actions/runner/issues/480
      image: ghcr.io/unittestbot/utbotcpp/base_env:24-11-2021
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        UTBOT_ALL: /utbot_distr
        UTBOT_INSTALL_DIR: /utbot_distr/install
        GRPC_PATH: /utbot_distr/install
        CLI_PATH: /utbot_distr/cli
        DOCKER_TAG: 24-11-2021
        ARTIFACT_DIR: utbot-artifact
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build UTBot and run unit tests
        run: |
          chmod +x docker/action-scripts/build-and-unit-tests.sh
          ./docker/action-scripts/build-and-unit-tests.sh
        shell: bash
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: UTBot unit tests logs
          path: server/build/logs
      - name: build VSCode plugin
        run: |
          chmod +x docker/action-scripts/build-vsix.sh
          ./docker/action-scripts/build-vsix.sh