name: Publish UTBot as an archive

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-18.04
    env:
      # Environment for the job and for the container is, sadly, duplicated
      # https://github.com/docker/compose/issues/1837
      VERSION: ${{ format('1.0.{0}', github.run_number) }}
      ARTIFACT_DIR: utbot-artifact
    container:
      # It is impossible to parametrize image via workflow environment,
      # so its name is hard-coded.
      # https://github.com/actions/runner/issues/480
      image: ghcr.io/unittestbot/utbotcpp/base_env:24-11-2021
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        UTBOT_ALL: /utbot_distr
        UTBOT_INSTALL_DIR: /utbot_distr/install
        GRPC_PATH: /utbot_distr/install
        CLI_PATH: /utbot_distr/cli
        VERSION: ${{ format('1.0.{0}', github.run_number) }}
        ARTIFACT_DIR: utbot-artifact
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build VSCode plugin
        run: |
          chmod +x docker/action-scripts/build-vsix.sh
          ./docker/action-scripts/build-vsix.sh
      - name: build UTBot
        run: |
          chmod +x docker/action-scripts/build-utbot.sh
          ./docker/action-scripts/build-utbot.sh
        shell: bash
      - name: prepare UTBot release for Ubuntu
        run: |
          chmod +x docker/action-scripts/prepare-ubuntu-release.sh
          ./docker/action-scripts/prepare-ubuntu-release.sh
      - uses: actions/upload-artifact@v2
        with:
          name: utbot-release-${{ env.VERSION }}
          path: ${{ env.ARTIFACT_DIR }}