name: Publish UTBot base environment image
on:
#  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: base_env
  TAG: 20-10-2021

jobs:
  build-docker:
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{env.IMAGE_NAME}}-${{ env.TAG }}
          restore-keys: |
            ${{ runner.os }}-buildx-buildx

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{env.REGISTRY}}/${{github.repository}}/${{env.IMAGE_NAME}}
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: docker
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          file: docker/Dockerfile_base
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          build-args: |
            OPERATING_SYSTEM_TAG=18.04
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache